<?php $zip = $_GET['z']; ?><div class='forecast-loading'></div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script type='text/javascript' src='../js/master.js'></script><script type="text/javascript" async="" src="http://www.google-analytics.com/ga.js"></script>
<script type="text/javascript" async="" src="http://cdn.livechatinc.com/tracking.js"></script><script async="" src="//www.google-analytics.com/analytics.js"></script>
<script src="http://netweather.accuweather.com/adcbin/netweather_v2/netweatherV2ex.asp?partner=netweather&amp;zipcode=<?php echo $zip; ?>&amp;size=11&amp;target=_blank"></script>
<object id="netWxV2" width="728" height="72" name="netWxV2" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0">
<param name="movie" value="http://netwx.accuweather.com/netWx-V211.swf?zipcode=<?php echo $zip; ?>&amp;customtheme=&amp;theme=1&amp;metric=0&amp;target=_blank&amp;lang=eng&amp;url=&amp;video=&amp;category=&amp;logo=&amp;tStyle=normal&amp;partner=netweather&amp;myspace=0"> 
<param name="wmode" value="transparent"><param name="AllowScriptAccess" value="always"> 
<embed id="netWxV2" src="http://netwx.accuweather.com/netWx-V211.swf?zipcode=<?php echo $zip; ?>&amp;customtheme=&amp;theme=1&amp;metric=0&amp;target=_blank&amp;lang=eng&amp;url=&amp;video=&amp;category=&amp;logo=&amp;tStyle=normal&amp;partner=netweather&amp;myspace=0" width="728" height="72" name="netWxV2" wmode="transparent" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" allowscriptaccess="always"></object>
<script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga_netwx');ga_netwx('create', 'UA-31945348-1', 'auto', {'name': 'netwxTracker'});ga_netwx('netwxTracker.set', 'page', '/netweather/11');ga_netwx('netwxTracker.send', 'pageview', {'dimension1':  'netWeather','dimension2':  ((document.domain) ? document.domain.split('.').join('-') : 'netWeather_NoDomain'),'dimension3':'netweather','dimension4':  'netweather_11'});</script>
<script>$(document).ready(function(){ $(".forecast-loading").delay(2000).fadeOut(200, function(){ $(this).remove(); }); });</script>